import jp.ac.uryukyu.ie.e215135.Dealer;
import jp.ac.uryukyu.ie.e215135.GameMaster;
import jp.ac.uryukyu.ie.e215135.Player;
import jp.ac.uryukyu.ie.e215135.View;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */


public class Main {
    public static void main(String[] args) {
        Player player = new Player();
        Dealer dealer = new Dealer();
        View view = new View();
        GameMaster gameMaster = new GameMaster(player, dealer, view);
        gameMaster.gameProgress();
    }
}
