/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.ac.uryukyu.ie.e215135;

public class Main {
    public static void main(String[] args) {
        System.out.println("Hello!!");
    }
}
