/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.ac.uryukyu.ie.e215135;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class DealerTest {
    @Test void checkDealer() {
        Dealer dealer = new Dealer();
        for (int i=0; i<2; i++){
            dealer.dealCard(dealer);
        }
        assertEquals(2,dealer.getCards().size());
        assertNotNull(dealer.getCards().get(0).getNum());
    }
}
